import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — SponsorSpark",
};

export default function TermsPage() {
  return (
    <article className="prose-basic mx-auto max-w-3xl">
      <div className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900">
        <strong>Template — not legal advice.</strong> These Terms are a starting draft. Because SponsorSpark
        involves minors and commercial arrangements, have them reviewed and finalized by a qualified attorney
        and complete the bracketed placeholders before launch.
      </div>

      <h1>Terms of Service</h1>
      <p><em>Last updated: [DATE]</em></p>

      <h2>1. Acceptance of terms</h2>
      <p>
        By using SponsorSpark (the &quot;Service&quot;), you agree to these Terms. If you do not agree, do not
        use the Service.
      </p>

      <h2>2. Eligibility &amp; parental responsibility</h2>
      <p>
        You must be at least 18 years old to create an account. If the Service is used in connection with an
        athlete under 18, you represent that you are that athlete&apos;s <strong>parent or legal guardian</strong>,
        that you consent to the processing described in our Privacy Policy, and that you are solely responsible
        for all activity conducted on the minor&apos;s behalf, including any outreach you choose to send.
      </p>

      <h2>3. What the Service is</h2>
      <p>
        SponsorSpark provides <strong>educational and drafting tools</strong>: it generates media kits, suggests
        categories of potential sponsors, and drafts outreach messages. Using the Service does not guarantee any
        sponsorship, income, or result.
      </p>

      <h2>4. Not professional advice</h2>
      <p>
        The Service does <strong>not</strong> provide legal, financial, tax, or contractual advice. Sponsorship
        agreements involving a minor can trigger important legal and tax obligations (including rules about
        contracts with minors, endorsements/disclosures, and, for scholastic athletes, eligibility rules such as
        NIL policies). <strong>Always review any agreement with a qualified attorney and, where relevant, a tax
        professional before signing.</strong>
      </p>

      <h2>5. AI-generated content</h2>
      <p>
        Outputs are generated by AI and may be inaccurate, incomplete, or outdated. You are responsible for
        reviewing and editing all outputs before use, and for ensuring any claims (statistics, achievements,
        endorsements) are truthful and comply with applicable advertising and disclosure rules.
      </p>

      <h2>6. Acceptable use</h2>
      <ul>
        <li>Do not enter false information or impersonate others.</li>
        <li>Do not enter a minor&apos;s sensitive personal details (see Privacy Policy).</li>
        <li>Do not use the Service for unlawful, harmful, or deceptive purposes.</li>
        <li>Do not attempt to disrupt, reverse engineer, or abuse the Service.</li>
      </ul>

      <h2>7. Accounts</h2>
      <p>You are responsible for safeguarding your account credentials and for all activity under your account.</p>

      <h2>8. Payments</h2>
      <p>
        Paid plans, if offered, are billed as described at checkout. [Describe billing cycle, refunds, and
        cancellation.] Prices may change with notice.
      </p>

      <h2>9. Intellectual property</h2>
      <p>
        We own the Service and its software. Content you generate for your athlete is yours to use; you grant us
        a limited license to process it solely to provide the Service.
      </p>

      <h2>10. Disclaimers</h2>
      <p>
        The Service is provided &quot;as is&quot; without warranties of any kind, to the fullest extent permitted
        by law. We do not warrant that outputs are accurate or that the Service will be uninterrupted or
        error-free.
      </p>

      <h2>11. Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, SponsorSpark will not be liable for indirect, incidental, or
        consequential damages, or for lost profits or lost opportunities, arising from your use of the Service.
        [Consider a liability cap.]
      </p>

      <h2>12. Indemnification</h2>
      <p>
        You agree to indemnify and hold SponsorSpark harmless from claims arising out of your use of the Service,
        your content, or your outreach to third parties.
      </p>

      <h2>13. Governing law</h2>
      <p>These Terms are governed by the laws of [state/country], without regard to conflict-of-laws rules.</p>

      <h2>14. Changes</h2>
      <p>We may update these Terms; continued use after changes means you accept them.</p>

      <h2>15. Contact</h2>
      <p>[support@sponsorspark.com], [company legal address].</p>
    </article>
  );
}
